name: Lighthouse Check
on: [push]

jobs:
  lighthouse-check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - run: mkdir /tmp/artifacts
    - name: Run Lighthouse
      uses: lighthouse-check-action@master
      with:
        outputDirectory: /tmp/artifacts
        urls: 'https://tataclicq.com,https://www.tatacliq.com/utsa-by-westside-aqua-embroidered-a-line-kurta/p-mp000000016265479'
    - name: Upload artifacts
      uses: actions/upload-artifact@master
      with:
        name: Lighthouse reports
        path: /tmp/artifacts
