name: LHCI-output-webhook
'on': push
jobs:
  output-webhook:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use output for sending data to API.
        id: LHCIAction
        uses: ./
        with:
          urls: |
            https://www.tatacliq.com
      - name: Webhook
        uses: denar90/webhook-action@0.1.0
        with:
          webhookUrl: '${{secrets.WEB_VITALS_HOOK}}'
          data: '{"text": "hum land kar rahe hai please help" }'
