---
name: LHCI-output-webhook
on:
  - push
jobs:
  lighthouse:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js 16.x
        uses: actions/setup-node@v1
        with:
          node-version: 16.x
      - name: Audit URLs using Lighthouse
        id: LHCIAction
        uses: treosh/lighthouse-ci-action@v3
        with:
          urls: |
            https://www.tatacliq.com
          uploadArtifacts: true
          temporaryPublicStorage: true
      - name: Generate URLs
        id: htmlPath
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.LHCI_GITHUB_APP_TOKEN }}
          script: >
            const htmlPath =
            JSON.parse('${{steps.LHCIAction.outputs.manifest}}')[0].htmlPath;

            const performance = JSON.parse('${{steps.LHCIAction.outputs.manifest}}')[0].summary['performance'] * 100;

            const accessibility = JSON.parse('${{steps.LHCIAction.outputs.manifest}}')[0].summary['accessibility'] * 100;

            const bestPractices = JSON.parse('${{steps.LHCIAction.outputs.manifest}}')[0].summary['best-practices'] * 100;

            const seo = JSON.parse('${{steps.LHCIAction.outputs.manifest}}')[0].summary['seo'] * 100;

            const pwa = JSON.parse('${{steps.LHCIAction.outputs.manifest}}')[0].summary['pwa'] * 100;

            const links = JSON.parse('${{steps.LHCIAction.outputs.links}}')['https://www.tatacliq.com/'];

            console.log('resultsPath','${{steps.LHCIAction.outputs.resultsPath}}');

            console.log('links','${{steps.LHCIAction.outputs.links}}');

            console.log('assertionResults','${{steps.LHCIAction.outputs.assertionResults}}');

            console.log('manifest','${{steps.LHCIAction.outputs.manifest}}');

            const bodyData = {
              "contentType": "application/vnd.microsoft.card.hero",
              "content": {
                "title": "Seattle Center Monorail",
                "subtitle": "Seattle Center Monorail",
                "text": "The Seattle Center Monorail is an elevated train line between Seattle Center (near the Space Needle) and downtown Seattle. It was built for the 1962 World's Fair. Its original two trains, completed in 1961, are still in service.",
                "images": [
                  {
                    "url":"https://upload.wikimedia.org/wikipedia/commons/thumb/4/49/Seattle_monorail01_2008-02-25.jpg/1024px-Seattle_monorail01_2008-02-25.jpg"
                  }
                ],
                "buttons": [
                  {
                    "type": "openUrl",
                    "title": "Official website",
                    "value": "https://www.seattlemonorail.com"
                  },
                  {
                    "type": "openUrl",
                    "title": "Wikipeda page",
                    "value": "https://en.wikipedia.org/wiki/Seattle_Center_Monorail"
                  }
                ]
              }
            }

            function sendRequest(data) {
              fetch('${{secrets.WEB_VITALS_HOOK}}', {
                method: "POST",
                headers: {'Content-Type': 'application/json'}, 
                body: JSON.stringify(data)
              }).then(res => {
                console.log("Request complete! response:", res);
              });
            }

            sendRequest(bodyData);

            console.log(bodyData);

          # const htmlPath = JSON.stringify(JSON.parse('${{steps.LHCIAction.outputs.manifest}}')[0].htmlPath);
          # core.setOutput('htmlPath', htmlPath);
      # - name: Deploy Stage
      #   uses: fjogeleit/http-request-action@v1
      #   with:
      #     url: '${{secrets.WEB_VITALS_HOOK}}'
      #     method: POST
      #     customHeaders: '{"Content-Type": "application/json"}'
      #     data: |
      #         {
      #           "type":"message",
      #           "attachments":[
      #               {
      #                 "contentType":"application/vnd.microsoft.card.adaptive",
      #                 "contentUrl":null,
      #                 "content":{
      #                     "$schema":"http://adaptivecards.io/schemas/adaptive-card.json",
      #                     "type":"AdaptiveCard",
      #                     "version":"1.2",
      #                     "body":[
      #                         {
      #                         "type": "TextBlock",
      #                         "text": 'Lighthouse Report ${{steps.htmlPath.outputs.htmlPath}}'
      #                         }
      #                     ]
      #                 }
      #               }
      #           ]
      #         }