name: LHCI-output-webhook
'on':
  - push
jobs:
  lighthouse:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Use Node.js 16.x
        uses: actions/setup-node@v1
        with:
          node-version: 16.x

      - name: Install dependencies
        run: npm install

      - name: Run Lighthouse audit
        run: npx lighthouse-ci https://www.tatacliq.com --output=json --output-path=lighthouse-report.json

      - name: Parse Lighthouse report
        run: |
          const fs = require('fs');
          const report = JSON.parse(fs.readFileSync('./lighthouse-report.json', 'utf8'));
          console.log(report);
          const metrics = report.categories.performance;
          const score = metrics.score;
          const interactive = metrics.metrics.interactive.value;
          const speedIndex = metrics.metrics.speedIndex.value;
          console.log(`Score: ${score}`);
          console.log(`Interactive: ${interactive}`);
          console.log(`Speed Index: ${speedIndex}`);
