name: LHCI-output-webhook
'on': push
jobs:
  output-webhook:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use output for sending data to API.
        id: LHCIAction
        uses: ./
        with:
          urls: |
            https://www.tatacliq.com
      - name: Webhook
        uses: denar90/webhook-action@0.1.1
        with:
          webhookUrl: >-
            https://tataunistore0.webhook.office.com/webhookb2/e5a9fb0f-a13d-41b9-aed8-91bb069e624c@33aa0ee4-90f0-486d-83c3-6fada33eb801/IncomingWebhook/76c1fbb7852b410189bcc843c10dee9a/26948857-23f9-46b7-bbf8-d60798503421
          data: |
            {"type": "message","text": "This is reply from bot!"}
