name: LHCI-output-webhook
'on':
  - push
jobs:
  lighthouse:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js 16.x
        uses: actions/setup-node@v1
        with:
          node-version: 16.x
      - name: Audit URLs using Lighthouse
        id: LHCIAction
        uses: treosh/lighthouse-ci-action@v3
        with:
          urls: |
            https://www.tatacliq.com
          uploadArtifacts: true
          temporaryPublicStorage: true
      - name: Deploy Stage
        uses: fjogeleit/http-request-action@v1
        with:
          url: '${{secrets.WEB_VITALS_HOOK}}'
          method: POST
          customHeaders: '{"Content-Type": "application/json"}'
          data: |
              {
                "type":"message",
                "attachments":[
                    {
                      "contentType":"application/vnd.microsoft.card.adaptive",
                      "contentUrl":null,
                      "content":{
                          "$schema":"http://adaptivecards.io/schemas/adaptive-card.json",
                          "type":"AdaptiveCard",
                          "version":"1.2",
                          "body":[
                              {
                              "type": "TextBlock",
                              "text": "Lighthouse report ${{steps.LHCIAction.outputs.links}}"
                              }
                          ]
                      }
                    }
                ]
              }
