# Example of output usage
name: LHCI-output-webhook
on: push
jobs:
  output-webhook:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use output for sending data to API.
        id: LHCIAction
        uses: ./
        with:
          urls: |
            https://www.tatacliq.com
      - name: Webhook
        uses: denar90/webhook-action@0.1.1
        with:
          webhookUrl: ${{secrets.WEB_VITALS_HOOK}}
          data: '{"@type": "MessageCard",
          "@context": "http://schema.org/extensions",
          "themeColor": "0076D7",
          "summary": "Attention Light House",
              "sections": [{
        "activityTitle": "Light house Report",
        "activitySubtitle": "On Project Tango",
        "activityImage": "https://teamsnodesample.azurewebsites.net/static/img/image5.png",
        "facts": [{
            "name": "Assigned to",
            "value": "Web Team"
        }, {
            "name": "Light House Data",
            "value": "${{steps.LHCIAction.outputs.manifest[0].summary}}"
        }],
        "markdown": true
    }],
    }'
